### ISSUE TITLE
[PE-D][Tester D] list command does not show animals in alphabetical order

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-3/tp#126]
![image.png](https://raw.githubusercontent.com/thaddeusong/ped/main/files/243d0fff-87fb-49b9-a331-fb3421246a48.png)

The user guide mentions that the `list` command should sort the list by alphabetical name order, but it does not.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: thaddeusong/ped#1

**Comment by bkjwjason** [comment]
Same as #176
