### ISSUE TITLE
[PE-D][Tester E] Edit error message should describe `INDEX` input restrictions when input is `edit 0 ...`

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-3/tp#130]
**Example:**

User types: `edit 0 n/New Name`

**Expected:**

The app notifies me of an invalid input, and describes the correct requirements for the command. 

**Actual:**

```
Invalid command format! 
Example: edit 1 n/ChangGoose da/2019-01-01 s/Dog 
```

As there are no mentions that `INDEX` must be a positive integer in the error, it might not be obvious what the issue is unless I also refer to the UG. This is also in contrast to other commands which specifically tell me that the `INDEX` is positive-integer-only.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: wxwern/ped#1

**Comment by bkjwjason** [comment]
@Blizzeracz  Since Error Message cannot be enhanced, can state in the UG that INDEX must be a positive integer, else it will output Invalid Command format


See also #137 , need to update UG (edit by index and not ID)
