### ISSUE TITLE
[PE-D][Tester C] Application did not exit with 'Exit' Command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-3/tp#133]
**Description**
Application did not exit with 'Exit' Command, as exit command mentioned in the UG

**Steps to reproduce**
1. open the jar file application
2. type in 'exit' in command line

**Outcome**
* Application shows "Unknown command error"

**Expected outcome**
* Application should exit

**Screenshot**

![Screenshot 2023-11-03 at 16.27.41.png](https://raw.githubusercontent.com/marioalvaro/ped/main/files/3f928b59-7391-437f-838d-e88452b1f924.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: marioalvaro/ped#3

**Comment by bkjwjason** [comment]
#163 
#153
#155
