### ISSUE TITLE
[PE-D][Tester D] Help command does not work for deletetask command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-3/tp#134]
The help command does not provide any details about the deletetask command.
![image.png](https://raw.githubusercontent.com/thaddeusong/ped/main/files/4a165fed-7cfc-4aa0-a930-e7707470136f.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: thaddeusong/ped#4

**Comment by bkjwjason** [comment]
Same as #161
