### ISSUE TITLE
[PE-D][Tester D] Edit command does not show the Date of Birth tag in command result message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-3/tp#140]
![image.png](https://raw.githubusercontent.com/thaddeusong/ped/main/files/25f3ede3-e1cf-457e-8567-06b1d0355f6d.png)

After using the edit command, the result message does not have the "Date of Birth:" preceding the Date of Birth. Only the date is shown in the result message.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: thaddeusong/ped#6

**Comment by bkjwjason** [comment]
Minor issue, remember to include DoB
