### ISSUE TITLE
[PE-D][Tester D] Unimplemented tag specified in documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-3/tp#147]
![image.png](https://raw.githubusercontent.com/thaddeusong/ped/main/files/5f358dcc-fc83-4d8c-886e-954eb723a238.png)
"t/" tag is specified here, but it is not implemented.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: thaddeusong/ped#8

**Comment by bkjwjason** [comment]
To Remove from UG
