### ISSUE TITLE
[PE-D][Tester E] The task list should include index numbers for easier reference

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-3/tp#157]
The task list currently shows the following:

![screenshot.png](https://raw.githubusercontent.com/wxwern/ped/main/files/3b285b04-5116-4913-8dc0-49d957c4637a.png)

But all commands related to manipulating tasks utilise the `INDEX` of the task. 

If I have, say, 10+ tasks for a pet, it starts getting impractical to actually figure out what index each task is - I need to manually count the index up to mark a task as done/undone or delete them, which is prone to errors on larger lists.

Hence, it would be great if there is the numeric index (`1.`, `2.`, etc.) shown just like the pet list.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: wxwern/ped#5

**Comment by bkjwjason** [comment]
Same as #154 #139
