### ISSUE TITLE
[PE-D][Tester E] The required format for searching for dates is not specified

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-3/tp#165]
It is possible to set dates using alternative formats, like `edit 1 db/20220909` and `edit 1 db/25 Dec 2020`

However, searching for dates **requires** the exact format YYYY-MM-DD, so `search db/20220909` does not work.

This should be clearly documented in the UG or command outputs, or the search function be revamped for consistency. Otherwise, a user who exclusively types in the format of something like `15 Oct 2023` when inputting data will not be able to search for dates in the same format, and may thus be confused.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: wxwern/ped#7

**Comment by bkjwjason** [comment]
Thoughts? @euchangxian @wjayee 

If we stick to `YYYY-MM-DD` then we should change the DoA and DoB format in add and edit, else we include the other `date` formatting for search as well

**Comment by bkjwjason** [comment]
Will be sticking to `YYYY-MM-DD` for dates , specified in UG as seen in #186
