### ISSUE TITLE
[PE-D][Tester B] Inaccurate error message for invalid prefixes for the search command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-3/tp#167]
Upon entering `search d/something` the `d/` prefix is not recognised, which is valid, but the error message is not specific to explain which prefixes to use. It would be beneficial to add a more descriptive error message in this case.

![Screenshot 2023-11-03 at 5.13.19 PM.png](https://raw.githubusercontent.com/gongg21/ped/main/files/613c7945-251a-42d6-8407-b4d794aecae3.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: gongg21/ped#8

**Comment by wjayee** [comment]
Can update future implementations to have a more accurate error message description. 
Will not update in v1.4 as it is not strictly incorrect.
