### ISSUE TITLE
[PE-D][Tester E] UG incorrectly claims that `delete` deletes by ID in a few places

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-3/tp#168]
The `delete` command deletes by `INDEX`. However, there are occasional incorrect mentions of its behaviour:

In the quick start guide:

> `delete 3` : Deletes the animal with ID 3.

In the end-of-page command summary:

> `delete ID`

This might be dangerous as it can lead to incorrect deletions if misinterpreted by the user, since `ID` and `INDEX` are both integers and can both plausibly have the same number when there are more than thousands of records.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: wxwern/ped#8

**Comment by bkjwjason** [comment]
Change to `INDEX` in UG
